// Generates src/app/core/version.ts from package.json + the current git commit.
// Runs as a pre-script before start / build / watch (see package.json), so the
// footer always renders the version and commit that this build was cut from.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, '..');
const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf8'));

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: rootDir }).toString().trim();
} catch {
  // Not a git checkout (e.g. a shallow CI export) — leave the placeholder.
}

const contents = `// Generated by scripts/gen-version.mjs on each build. Do not edit by hand.
export const VERSION = { app: '${pkg.version}', commit: '${commit}' } as const;
`;

writeFileSync(join(rootDir, 'src/app/core/version.ts'), contents);
console.log(`version.ts → v${pkg.version} (${commit})`);
